name: eoapi-workshop
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - gdal=3.10
  - python=3.12
  - rust
  - pip
  - boto3
  - httpx 
  - ipywidgets
  - pystac
  - pystac-client
  - rasterio
  - rio-stac
  - shapely
  - pip:
    - pypgstac[psycopg]==0.9.8
    - stactools-sentinel2
