[workspace]
authors = ["Alex Mandel <tech@wildintellect.com>"]
channels = ["conda-forge"]
name = "eoapi-workshop"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mystmd = ">=1.6.2,<2"
