#!/bin/bash

# Workshop configuration
export WORKSHOP_PROJECT_ID="workshop"

# API endpoints - publicly accessible
export STAC_API_ENDPOINT="https://workshop-stac.eoapi.dev"
export TITILER_PGSTAC_API_ENDPOINT="https://workshop-raster.eoapi.dev"
export TIPG_API_ENDPOINT="https://workshop-vector.eoapi.dev"
export CONFIG_API_ENDPOINT="https://workshop-config.eoapi.dev"

# AWS configuration for public data access
export AWS_NO_SIGN_REQUEST=TRUE

exec "$@"
